# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
theme_advanced_toolbar_location: "top"
theme_advanced_toolbar_align : "left"


width : "500"
height : "300"

theme_advanced_blockformats : "p,h1,h2,h3,h4,h5,h6"


theme_advanced_buttons1 : "formatselect,bold,italic,separator,bullist,numlist,separator,outdent,indent,separator,link,unlink,separator,justifyleft,justifycenter,justifyright"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""

#http://wiki.moxiecode.com/index.php/TinyMCE:Control_reference





#theme_advanced_disable : "bold,italic"



plugins:
 - table
 - fullscreen
 - paste




