require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScreenCastsController do

  # This should return the minimal set of attributes required to create a valid
  # ScreenCast. As you add validations to ScreenCast, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all screen_casts as @screen_casts" do
      screen_cast = ScreenCast.create! valid_attributes
      get :index
      assigns(:screen_casts).should eq([screen_cast])
    end
  end

  describe "GET show" do
    it "assigns the requested screen_cast as @screen_cast" do
      screen_cast = ScreenCast.create! valid_attributes
      get :show, :id => screen_cast.id.to_s
      assigns(:screen_cast).should eq(screen_cast)
    end
  end

  describe "GET new" do
    it "assigns a new screen_cast as @screen_cast" do
      get :new
      assigns(:screen_cast).should be_a_new(ScreenCast)
    end
  end

  describe "GET edit" do
    it "assigns the requested screen_cast as @screen_cast" do
      screen_cast = ScreenCast.create! valid_attributes
      get :edit, :id => screen_cast.id.to_s
      assigns(:screen_cast).should eq(screen_cast)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScreenCast" do
        expect {
          post :create, :screen_cast => valid_attributes
        }.to change(ScreenCast, :count).by(1)
      end

      it "assigns a newly created screen_cast as @screen_cast" do
        post :create, :screen_cast => valid_attributes
        assigns(:screen_cast).should be_a(ScreenCast)
        assigns(:screen_cast).should be_persisted
      end

      it "redirects to the created screen_cast" do
        post :create, :screen_cast => valid_attributes
        response.should redirect_to(ScreenCast.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved screen_cast as @screen_cast" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenCast.any_instance.stub(:save).and_return(false)
        post :create, :screen_cast => {}
        assigns(:screen_cast).should be_a_new(ScreenCast)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenCast.any_instance.stub(:save).and_return(false)
        post :create, :screen_cast => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested screen_cast" do
        screen_cast = ScreenCast.create! valid_attributes
        # Assuming there are no other screen_casts in the database, this
        # specifies that the ScreenCast created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScreenCast.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => screen_cast.id, :screen_cast => {'these' => 'params'}
      end

      it "assigns the requested screen_cast as @screen_cast" do
        screen_cast = ScreenCast.create! valid_attributes
        put :update, :id => screen_cast.id, :screen_cast => valid_attributes
        assigns(:screen_cast).should eq(screen_cast)
      end

      it "redirects to the screen_cast" do
        screen_cast = ScreenCast.create! valid_attributes
        put :update, :id => screen_cast.id, :screen_cast => valid_attributes
        response.should redirect_to(screen_cast)
      end
    end

    describe "with invalid params" do
      it "assigns the screen_cast as @screen_cast" do
        screen_cast = ScreenCast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenCast.any_instance.stub(:save).and_return(false)
        put :update, :id => screen_cast.id.to_s, :screen_cast => {}
        assigns(:screen_cast).should eq(screen_cast)
      end

      it "re-renders the 'edit' template" do
        screen_cast = ScreenCast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenCast.any_instance.stub(:save).and_return(false)
        put :update, :id => screen_cast.id.to_s, :screen_cast => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested screen_cast" do
      screen_cast = ScreenCast.create! valid_attributes
      expect {
        delete :destroy, :id => screen_cast.id.to_s
      }.to change(ScreenCast, :count).by(-1)
    end

    it "redirects to the screen_casts list" do
      screen_cast = ScreenCast.create! valid_attributes
      delete :destroy, :id => screen_cast.id.to_s
      response.should redirect_to(screen_casts_url)
    end
  end

end
