require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TextContentsController do

  # This should return the minimal set of attributes required to create a valid
  # TextContent. As you add validations to TextContent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { identity: 'abc', title: 'my title', body: 'content' }
  end

  # TODO test no-access for anonymous and ordinary user
  describe "as anonymous user" do

  end

  describe "as normal user" do

  end

  describe "as admin user"


  before (:each) do
    @user = Factory(:admin)
    sign_in(@user)
  end

  describe "GET index" do
    it "assigns all text_contents as @text_contents" do
      text_content = TextContent.create! valid_attributes
      get :index
      assigns(:text_contents).should eq([text_content])
    end
  end

  describe "GET show" do
    it "assigns the requested text_content as @text_content" do
      text_content = TextContent.create! valid_attributes
      get :show, :id => text_content.id.to_s
      assigns(:text_content).should eq(text_content)
    end
  end

  describe "GET new" do
    it "assigns a new text_content as @text_content" do
      get :new
      assigns(:text_content).should be_a_new(TextContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested text_content as @text_content" do
      text_content = TextContent.create! valid_attributes
      get :edit, :id => text_content.id.to_s
      assigns(:text_content).should eq(text_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TextContent" do
        expect {
          post :create, :text_content => valid_attributes
        }.to change(TextContent, :count).by(1)
      end

      it "assigns a newly created text_content as @text_content" do
        post :create, :text_content => valid_attributes
        assigns(:text_content).should be_a(TextContent)
        assigns(:text_content).should be_persisted
      end

      it "redirects to the created text_content" do
        post :create, :text_content => valid_attributes
        #response.should redirect_to(TextContent.last)
        response.should redirect_to text_contents_path
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved text_content as @text_content" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextContent.any_instance.stub(:save).and_return(false)
        post :create, :text_content => {}
        assigns(:text_content).should be_a_new(TextContent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TextContent.any_instance.stub(:save).and_return(false)
        post :create, :text_content => {}
        #response.should render_template("new")
        response.should redirect_to text_contents_path # FIXME why?
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested text_content" do
        text_content = TextContent.create! valid_attributes
        # Assuming there are no other text_contents in the database, this
        # specifies that the TextContent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TextContent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => text_content.id, :text_content => {'these' => 'params'}
      end

      it "assigns the requested text_content as @text_content" do
        text_content = TextContent.create! valid_attributes
        put :update, :id => text_content.id, :text_content => valid_attributes
        assigns(:text_content).should eq(text_content)
      end

      it "redirects to the text_content" do
        text_content = TextContent.create! valid_attributes
        put :update, :id => text_content.id, :text_content => valid_attributes
        #response.should redirect_to(text_content)
        response.should redirect_to text_contents_path
      end
    end

    describe "with invalid params" do
      it "assigns the text_content as @text_content" do
        text_content = TextContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextContent.any_instance.stub(:save).and_return(false)
        put :update, :id => text_content.id.to_s, :text_content => {}
        assigns(:text_content).should eq(text_content)
      end

      it "re-renders the 'edit' template" do
        text_content = TextContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TextContent.any_instance.stub(:save).and_return(false)
        put :update, :id => text_content.id.to_s, :text_content => {}
        #response.should render_template("edit")
        response.should redirect_to text_contents_path # FIXME why?
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested text_content" do
      text_content = TextContent.create! valid_attributes
      expect {
        delete :destroy, :id => text_content.id.to_s
      }.to change(TextContent, :count).by(-1)
    end

    it "redirects to the text_contents list" do
      text_content = TextContent.create! valid_attributes
      delete :destroy, :id => text_content.id.to_s
      response.should redirect_to(text_contents_url)
    end
  end

end
