require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VideoCastsController do

  # This should return the minimal set of attributes required to create a valid
  # VideoCast. As you add validations to VideoCast, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all video_casts as @video_casts" do
      video_cast = VideoCast.create! valid_attributes
      get :index
      assigns(:video_casts).should eq([video_cast])
    end
  end

  describe "GET show" do
    it "assigns the requested video_cast as @video_cast" do
      video_cast = VideoCast.create! valid_attributes
      get :show, :id => video_cast.id.to_s
      assigns(:video_cast).should eq(video_cast)
    end
  end

  describe "GET new" do
    it "assigns a new video_cast as @video_cast" do
      get :new
      assigns(:video_cast).should be_a_new(VideoCast)
    end
  end

  describe "GET edit" do
    it "assigns the requested video_cast as @video_cast" do
      video_cast = VideoCast.create! valid_attributes
      get :edit, :id => video_cast.id.to_s
      assigns(:video_cast).should eq(video_cast)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VideoCast" do
        expect {
          post :create, :video_cast => valid_attributes
        }.to change(VideoCast, :count).by(1)
      end

      it "assigns a newly created video_cast as @video_cast" do
        post :create, :video_cast => valid_attributes
        assigns(:video_cast).should be_a(VideoCast)
        assigns(:video_cast).should be_persisted
      end

      it "redirects to the created video_cast" do
        post :create, :video_cast => valid_attributes
        response.should redirect_to(VideoCast.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved video_cast as @video_cast" do
        # Trigger the behavior that occurs when invalid params are submitted
        VideoCast.any_instance.stub(:save).and_return(false)
        post :create, :video_cast => {}
        assigns(:video_cast).should be_a_new(VideoCast)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VideoCast.any_instance.stub(:save).and_return(false)
        post :create, :video_cast => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested video_cast" do
        video_cast = VideoCast.create! valid_attributes
        # Assuming there are no other video_casts in the database, this
        # specifies that the VideoCast created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VideoCast.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => video_cast.id, :video_cast => {'these' => 'params'}
      end

      it "assigns the requested video_cast as @video_cast" do
        video_cast = VideoCast.create! valid_attributes
        put :update, :id => video_cast.id, :video_cast => valid_attributes
        assigns(:video_cast).should eq(video_cast)
      end

      it "redirects to the video_cast" do
        video_cast = VideoCast.create! valid_attributes
        put :update, :id => video_cast.id, :video_cast => valid_attributes
        response.should redirect_to(video_cast)
      end
    end

    describe "with invalid params" do
      it "assigns the video_cast as @video_cast" do
        video_cast = VideoCast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VideoCast.any_instance.stub(:save).and_return(false)
        put :update, :id => video_cast.id.to_s, :video_cast => {}
        assigns(:video_cast).should eq(video_cast)
      end

      it "re-renders the 'edit' template" do
        video_cast = VideoCast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VideoCast.any_instance.stub(:save).and_return(false)
        put :update, :id => video_cast.id.to_s, :video_cast => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested video_cast" do
      video_cast = VideoCast.create! valid_attributes
      expect {
        delete :destroy, :id => video_cast.id.to_s
      }.to change(VideoCast, :count).by(-1)
    end

    it "redirects to the video_casts list" do
      video_cast = VideoCast.create! valid_attributes
      delete :destroy, :id => video_cast.id.to_s
      response.should redirect_to(video_casts_url)
    end
  end

end
